version: '3.5'

services:
  database:
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:14.3-alpine
    networks:
      - backend-network

  server:
    container_name: server
    build:
      context: .
    ports:
      - "8080:8080"  # Проброс порта для сервера
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    networks:
      - backend-network

networks:
  backend-network: