name: Backend-Service for smart contract NFT-Lending

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}

      - name: Pull and Tag Docker Postgres image
        run: |
          docker pull postgres:latest
          docker tag postgres:latest ghcr.io/${{ github.repository }}/postgres:latest
          docker push ghcr.io/${{ github.repository }}/postgres:latest
    
      - name: Build Docker backend image
        run: |
          docker build . -f Dockerfile -t testrep_backend
    
      - name: Tag and push Docker backend image
        run: |
          docker tag testrep_backend:latest ghcr.io/${{ github.repository }}/backend:latest
          docker push ghcr.io/${{ github.repository }}/backend:latest
    