version: '3'
services:
  backend-service:
    build:
      context: .
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=your_postgres_user
      - POSTGRES_PASSWORD=your_postgres_password
      - POSTGRES_DBNAME=your_database_name
      - POSTGRES_PORT=5432
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: postgres
    environment:
      - POSTGRES_USER=your_postgres_user
      - POSTGRES_PASSWORD=your_postgres_password
      - POSTGRES_DB=your_database_name
