version: '3'
services:
    backend-service:
        build:
            context: .
            environment:
                - POSTGRES_HOST=localhost
                - POSTGRES_USER=postgres
                - POSTGRES_PASSWORD=postgres
                - POSTGRES_DBNAME=postgres
                - POSTGRES_PORT=5432
            depends_on:
                - db
            ports:
                - 8080:8080
            db:
                container_name: postgres
                image: postgres
                environment:
                    - POSTGRES_USER=your_postgres_user
                    - POSTGRES_PASSWORD=your_postgres_password
                    - POSTGRES_DB=your_database_name
